name: Feature Request
description: Suggest a new feature or improvement
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: What would you like to see added?
      placeholder: Explain your idea here...
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Why is this needed?
      description: Explain why this feature is important.
      placeholder: Who benefits? What problem does it solve?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: Any other solutions you tried?
    validations:
      required: false

